package me.stammberger.starcitizeninformer.models.ship;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class Actionscontainer {

    @SerializedName("additionals")
    @Expose
    public List<String> additionals = new ArrayList<>();

}
