package me.stammberger.starcitizeninformer.models.ship;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class Structuralcontainer {

    @SerializedName("cargocapacity")
    @Expose
    public String cargocapacity;
    @SerializedName("factorymaneuveringthrusters")
    @Expose
    public String factorymaneuveringthrusters;
    @SerializedName("factorypowerplant")
    @Expose
    public String factorypowerplant;
    @SerializedName("factorythruster")
    @Expose
    public String factorythruster;
    @SerializedName("heading")
    @Expose
    public String heading;
    @SerializedName("maneuveringthrusters")
    @Expose
    public String maneuveringthrusters;
    @SerializedName("maxcrew")
    @Expose
    public String maxcrew;
    @SerializedName("maxpowerplant")
    @Expose
    public String maxpowerplant;
    @SerializedName("maxprimarythruster")
    @Expose
    public String maxprimarythruster;
    @SerializedName("maxshield")
    @Expose
    public String maxshield;
    @SerializedName("shield")
    @Expose
    public String shield;

}
