package me.stammberger.starcitizeninformer.models.ship;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class Titlecontainer {

    @SerializedName("description")
    @Expose
    public String description;
    @SerializedName("manufacturer")
    @Expose
    public String manufacturer;
    @SerializedName("production")
    @Expose
    public String production;
    @SerializedName("role")
    @Expose
    public String role;
    @SerializedName("title")
    @Expose
    public String title;

}
