package me.stammberger.starcitizencompact.models.ship;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class Hardpointscontainer {

    @SerializedName("heading")
    @Expose
    public String heading;
    @SerializedName("hp-c1")
    @Expose
    public String hpC1;
    @SerializedName("hp-c2")
    @Expose
    public String hpC2;
    @SerializedName("hp-c3")
    @Expose
    public String hpC3;
    @SerializedName("hp-c4")
    @Expose
    public String hpC4;
    @SerializedName("hp-c5")
    @Expose
    public String hpC5;
    @SerializedName("hp-c6")
    @Expose
    public String hpC6;
    @SerializedName("hp-c7")
    @Expose
    public String hpC7;
    @SerializedName("hp-c8")
    @Expose
    public String hpC8;
    @SerializedName("hp-c9")
    @Expose
    public String hpC9;

}
