package me.stammberger.starcitizencompact.models.ship;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class Measurementcontainerheader {

    @SerializedName("beam")
    @Expose
    public String beam;
    @SerializedName("heading")
    @Expose
    public String heading;
    @SerializedName("height")
    @Expose
    public String height;
    @SerializedName("length")
    @Expose
    public String length;
    @SerializedName("mass")
    @Expose
    public String mass;

}
