package me.stammberger.starcitizencompact.models.ship;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class ShipData {

    @SerializedName("lastupdated")
    @Expose
    public String lastupdated;
    @SerializedName("manufacturers")
    @Expose
    public List<String> manufacturers = new ArrayList<>();
    @SerializedName("ships")
    @Expose
    public List<Ship> ships = new ArrayList<>();
    @SerializedName("statbox_headers")
    @Expose
    public List<StatboxHeader> statboxHeaders = new ArrayList<>();

}
