package me.stammberger.galactictavern.models.ship;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import me.stammberger.galactictavern.actions.GtActionCreator;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class ShipData {

    @SerializedName("lastupdated")
    @Expose
    public String lastupdated;
    @SerializedName("manufacturers")
    @Expose
    public List<String> manufacturers = new ArrayList<>();
    @SerializedName("ships")
    @Expose
    public List<Ship> ships = new ArrayList<>();

    /**
     * Link from ship id (name) to the ship data object in memory
     * <p>
     * TODO: Add a list to the json object to avoid creating this within the {@link GtActionCreator}
     */
    public LinkedHashMap<String, Ship> shipMap = new LinkedHashMap<>();

    @SerializedName("statbox_headers")
    @Expose
    public StatboxHeaders statboxHeaders;


}
