package me.stammberger.starcitizeninformer.models.ships;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import me.stammberger.starcitizeninformer.models.BaseModel;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class Ship extends BaseModel {

    @SerializedName("actionscontainer")
    @Expose
    public Actionscontainer actionscontainer;
    @SerializedName("hardpointscontainer")
    @Expose
    public Hardpointscontainer hardpointscontainer;
    @SerializedName("measurementcontainer")
    @Expose
    public Measurementcontainer measurementcontainer;
    @SerializedName("modularcontainer")
    @Expose
    public Modularcontainer modularcontainer;
    @SerializedName("propulsionscontainer")
    @Expose
    public Propulsionscontainer propulsionscontainer;
    @SerializedName("shipimgsmall")
    @Expose
    public String shipimgsmall;
    @SerializedName("shipimgsrc")
    @Expose
    public String shipimgsrc;
    @SerializedName("structuralcontainer")
    @Expose
    public Structuralcontainer structuralcontainer;
    @SerializedName("titlecontainer")
    @Expose
    public Titlecontainer titlecontainer;

    public Ship() {
        // at least for phones span count will always be 1 by default
        spanCount = 1;
    }

}
