package me.stammberger.starcitizeninformer.models.ships;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by: http://www.jsonschema2pojo.org/
 */
public class StatboxHeader {

    @SerializedName("titlecontainerheader")
    @Expose
    public Titlecontainerheader titlecontainerheader;
    @SerializedName("measurementcontainerheader")
    @Expose
    public Measurementcontainerheader measurementcontainerheader;
    @SerializedName("structuralcontainerheader")
    @Expose
    public Structuralcontainerheader structuralcontainerheader;
    @SerializedName("propulsionscontainerheader")
    @Expose
    public Propulsionscontainerheader propulsionscontainerheader;
    @SerializedName("hardpointscontainerheader")
    @Expose
    public Hardpointscontainerheader hardpointscontainerheader;
    @SerializedName("modularcontainerheader")
    @Expose
    public Modularcontainerheader modularcontainerheader;

}
